version: "3"
services:
  nginx:
    build: .
    image: gmontag/nginx-front:master
    links:
      - node
    ports:
      - "80:80"
      - "443:443"
    domainname: domain.com
    networks:
      - web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  web:
